#!/usr/bin/env bash

URL=$1

A=$(dig +short -t A $URL)
AAAA=$(dig +short -t AAAA $URL)
CNAME=$(dig +short -t CNAME $URL | sort)
MX=$(dig +short -t MX $URL | sort)
if [ -n "$A" ]; then echo -e "- **A:** $A\n"; fi
if [ -n "$AAAA" ]; then echo -e "- **AAAA:** $AAAA\n"; fi
if [ -n "$CNAME" ]; then echo -e "- **CNAME:** $CNAME\n"; fi
if [ -n "$MX" ]; then echo -e "- **MX:** $MX\n"; fi
