#!/usr/bin/env bash

DOMAIN=$1
shift
SUBDOMAINS="$@"

echo "# $DOMAIN"
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo -e "\n### WHOIS\n"
$DIR/domstat-whois "$DOMAIN"

echo -e "\n### DNS Records\n"

echo -e "\n$DOMAIN\n"
$DIR/domstat-zone "$DOMAIN"
$DIR/domstat-records "$DOMAIN"

for SUBDOMAIN in $SUBDOMAINS; do
  URL="$SUBDOMAIN.$DOMAIN"
  echo -e "\n$URL\n"
  $DIR/domstat-records "$URL"
done

echo -e "\n### Headers\n"

echo -e "$DOMAIN\n"
$DIR/domstat-head "$DOMAIN"

for SUBDOMAIN in $SUBDOMAINS; do
  URL="$SUBDOMAIN.$DOMAIN"
  echo -e "\n$URL\n"
  $DIR/domstat-head "$URL"
done
