#!/usr/bin/env bash

set -- $@
DOMAIN=$1
shift

echo -e "## DOMSTAT: $DOMAIN"
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# cd "$DOMAIN_DIR"
# mkdir -p {head,records,whois,zone}

echo -e "\n### WHOIS: $DOMAIN\n"
$DIR/domstat-whois "$DOMAIN"

echo -e "\n### ZONE: $DOMAIN\n"
$DIR/domstat-zone "$DOMAIN"

echo -e "\n### RECORDS: $DOMAIN\n"
$DIR/domstat-records "$DOMAIN"

echo -e "\n### HEAD: $DOMAIN\n"
$DIR/domstat-head "$DOMAIN"

while (( "$#" )); do
  URL="$1.$DOMAIN"

  echo -e "\n### SUBDOMAIN-RECORDS: $URL\n"
  $DIR/domstat-records "$URL"

  echo -e "\n### SUBDOMAIN-HEAD: $URL\n"
  $DIR/domstat-head "$URL"

  shift
done
