#!/usr/bin/env bash

URL=$1

for RECORD in NS SOA; do
  OUT=$(dig +short -t $RECORD $URL | sort)
  if [ -n "$OUT" ]; then
    OUT=$(echo -e "$OUT" | sed "s/^/- **$RECORD:** /")
    echo "$OUT"
  fi
done
